name: Build/Test for PR and collaborator push

on:
  # allows us to run workflows manually
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '.github/workflows/build_test_publish.yml'
      - '.github/workflows/changelog_test.yml'
      - 'docker/**'
      - 'doc/**'
  push:
    paths-ignore:
      - '.github/workflows/build_test_publish.yml'
      - '.github/workflows/changelog_test.yml'
      - 'docker/**'
      - 'doc/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ubuntu_versions : [
          20.04,
          22.04,
          ]
        pkg_mgr : [
            apt,
            conda,
        ]
    
    container:
      image: ghcr.io/cyclus/cyclus_${{ matrix.ubuntu_versions }}_${{ matrix.pkg_mgr }}/${{ matrix.pkg_mgr }}-deps

    steps:
      - name: Checkout and Build Cyclus
        uses: actions/checkout@v3

      - name: Building Cyclus
        run: |
          mkdir -p `python -m site --user-site`
          python install.py -j 2 --build-type=Release --core-version 999999.999999 --code_coverage
          echo "PATH=${HOME}/.local/bin:$PATH" >> "$GITHUB_ENV"
          echo "LD_LIBRARY_PATH=${HOME}/.local/lib:${HOME}/.local/lib/cyclus:$LD_LIBRARY_PATH" >> "$GITHUB_ENV"

      - name: Cyclus Unit Tests
        run: |
          cyclus_unit_tests

      - name: Cyclus Python Tests
        run: |
          cd tests && python -m pytest --ignore test_main.py

      - name: Install lcov for apt
        if: '${{ matrix.pkg_mgr }}' == 'apt'
        run: |
          apt update --fix-missing && apt install -y lcov
          echo "GCOV=/usr/bin/gcov" >> "$GITHUB_ENV"
      
      - name: Install lcov for conda
        if: '${{ matrix.pkg_mgr }}' == 'conda'
        run: |
            mamba install -y lcov
            echo "GCOV=/opt/conda/bin/x86_64-conda-linux-gnu-gcov" >> "$GITHUB_ENV"

      - name: Generate Coverage Report
        run: |
          lcov -c --rc lcov_branch_coverage=1 -d build/src -o ${HOME}/cyclus_coverage.info --gcov-tool ${{ env.GCOV }}
          lcov --remove ${HOME}/cyclus_coverage.info "/usr/*"
          {
            echo 'COVERAGE_SUMMARY<<EOF'
            lcov --summary ${HOME}/cyclus_coverage.info
            echo EOF
          } >> "$GITHUB_ENV"
          mkdir -p ${HOME}/cyclus_coverage/html
          genhtml ${HOME}/cyclus_coverage.info --output-directory ${HOME}/cyclus_coverage/html
          echo "artifactPath=${HOME}/cyclus_coverage/html/" >> $GITHUB_ENV
        
      - name: Upload Coverage Report Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          name: cyclus-coverage-report-${{ matrix.ubuntu-versions }}-${{ matrix.pkg_mgr }}
          path: ${{ env.artifactPath }}

      - name: Comment Coverage Summary to PR Discussion
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v6
        env:
          COMMENT_BODY: '${{ env.COVERAGE_SUMMARY }}'
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { COMMENT_BODY } = process.env;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `**Code Coverage Summary (${{ matrix.ubuntu_versions }}, ${{ matrix.pkg_mgr }})** 
              **Commit: [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})**
              ${COMMENT_BODY}`
            })