name: Downstream Testing

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '.github/workflows/build_test_publish.yml'
      - '.github/workflows/changelog_test.yml'
      - 'docker/**'
      - 'doc/**'
      - 'CHANGELOG.rst'
  push:
    paths-ignore:
      - '.github/workflows/build_test_publish.yml'
      - '.github/workflows/changelog_test.yml'
      - 'docker/**'
      - 'doc/**'
      - 'CHANGELOG.rst'

jobs:
  build-cyclus:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ubuntu_versions:
          - 20.04
          - 22.04
        pkg_mgr:
          - apt
          - conda

    name: Build Cyclus Docker Image
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: cyclus:${{ matrix.ubuntu_versions }}-${{ matrix.pkg_mgr }}
          outputs: type=docker,dest=/tmp/${{ matrix.ubuntu_versions }}-${{ matrix.pkg_mgr }}.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.ubuntu_versions }}-${{ matrix.pkg_mgr }}
          path: /tmp/${{ matrix.ubuntu_versions }}-${{ matrix.pkg_mgr }}.tar

  build-cycamore:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ubuntu_versions:
          - 20.04
          - 22.04
        pkg_mgr:
          - apt
          - conda

    needs: build-cyclus

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.ubuntu_versions }}-${{ matrix.pkg_mgr }}
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/${{ matrix.ubuntu_versions }}-${{ matrix.pkg_mgr }}.tar
          docker image ls -a
