name: OSX Build/Test Cyclus

on:
  # allows us to run workflows manually
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '.github/workflows/build_test.yml'
      - '.github/workflows/publish_latest.yml'
      - '.github/workflows/publish_release.yml'
      - '.github/workflows/changelog_test.yml'
      - '.github/workflows/code_coverage.yml'
      - '.github/workflows/rocky_build_test.yml'
      - 'doc/**'
      - 'CHANGELOG.rst'
  push:
    paths-ignore:
      - '.github/workflows/build_test.yml'
      - '.github/workflows/publish_latest.yml'
      - '.github/workflows/publish_release.yml'
      - '.github/workflows/changelog_test.yml'
      - '.github/workflows/code_coverage.yml'
      - '.github/workflows/rocky_build_test.yml'
      - 'doc/**'
      - 'CHANGELOG.rst'

jobs:
  build-test-ubuntu:
    strategy:
      fail-fast: false
      matrix:
        osx_versions : [
          macos-12,
          macos-13,
          macos-14,
        ]
    runs-on: [ "${{ matrix.osx_versions }}" ]

    steps:

      - name: Checkout Cyclus
        uses: actions/checkout@v4

      - name: Install Cyclus Dependencies
        id: brew-deps
        run: |
          brew install \
            gcc \
            make \
            cmake \
            pkg-config \
            boost \
            libxml2 \
            libxml++@4 \
            python3 \
            cython \
            sqlite \
            hdf5 \
            lapack \
            cbc \
            clp \
            jinja2-cli \
            numpy

      - name: Build Cyclus
        id: build-cyclus
        run: |
          ls $(brew --prefix gcc)/bin
          python install.py -j 4 --build-type Release --allow-milps --coin-root $(brew --prefix cbc) \
            -DCMAKE_C_COMPILER=$(brew --prefix gcc)/bin/gcc -DCMAKE_CXX_COMPILER=$(brew --prefix gcc)/bin/g++
            
      # - name: Unit Tests
      #   id: cyclus-unit-tests
      #   run: 

      - name: Checkout Cycamore
        if: ${{ github.event_name == 'pull_request' && steps.build-cyclus.outcome == 'success' }}
        uses: actions/checkout@v4
        with:
          repository: cyclus/cycamore
          path: ${{ github.workspace }}/cycamore

      - name: Checkout Cymetric
        if: ${{ github.event_name == 'pull_request' && steps.build-cycamore.outcome == 'success' }}
        uses: actions/checkout@v4
        with:
          repository: cyclus/cymetric
          path: ${{ github.workspace }}/cymetric